#!/bin/bash

# Configuração de Intalçao da pasta de arquivos.
USUARIO=root
GRUPO=libvirt-qemu

# Pacotes a ser instalados

sudo apt install qemu-kvm libvirt-clients libvirt-daemon-system
sudo apt-get install openssh-server

# Diretorio onde ficara os arquivos bases da maquinas virtuais

DIRETORIO=/var/lib/images

# Verificar se o diretorio ja existe.

if [ -d "$DIRETORIO" ]; then
echo "Diretorio já existe"
else
echo "Diretorio não existe"
mkdir $DIRETORIO
# Mudando o grupo do diretorio
chown -R $USUARIO.$GRUPO. $DIRETORIO
fi

# Configuração da interface de netwoking
echo"
#set up bridge and give it a static ip
auto br0
iface br0 inet static
        address 192.168.1.2
        netmask 255.255.255.0
        network 192.168.1.0
        broadcast 192.168.1.255
        gateway 192.168.1.1
        bridge_ports eth0
        bridge_stp off
        bridge_fd 0
        bridge_maxwait 0
        dns-nameservers 8.8.8.8

#allow autoconf for ipv6
iface br0 inet6 auto
        accept_ra 1
" >> /etc/network/interfaces
