#!/bin/bash
PCM(){ PROMPT ;clear; PMENU;}

PROMPT()
{ printf "${CE}\e[18;$(( ($(tput cols)-46 )/2+1))f<< PRESSIONE QUALQUER TECLA  PARA CONTINUAR >>${FC}";
read -e -n1 PRMPT ;
local PRMPT ;
}
 
PMENU() 
{
#GERACOR;
COLS;
}

MENU() {
	tput clear
	printf "${CE}\e[2;${POS2}f----------------------------------------"
	printf "\e[3;${POS1}f-------------- MENU USÚARIO --------------"
	printf "\e[4;${POS}f---\e[4;${POS3}f---"
	printf "\e[5;${POS}f---${CSM}    [1] Cadastrar       [2] Listar    ${CE}---"
	printf "\e[6;${POS}f---${CSM}    [3] Remover         [4] Alterar   ${CE}---"
#	printf "\e[7;${POS}f---${CSM}    [5] Opção 5         [6] Opção 6   ${CE}---"
	printf "\e[7;${POS}f---${CSM}               [8] Exit               ${CE}---"
	printf "\e[8;${POS}f---\e[8;${POS3}f---"
	printf "${CE}\e[9;${POS1}f------------------------------------------"
	printf "\e[10;${POS2}f----------------------------------------\n\n"$FC""
	read -p " OPÇãO: " -n1 OPC

	case "$OPC" in
	1) FUNCAO_01 ;;
	2) FUNCAO_02 ;;
	3) FUNCAO_03 ;;
	4) FUNCAO_04 ;;
	8) echo -e "\n\n Saindo...\n";sleep 0.5; exit ;;
	*) MSGM ; PMENU ;;
	esac
}

COLS() {

	COLS=$(tput cols)
	POS=$(((COLS-44)/2+1))
	POS1=$((POS+1))
	POS2=$((POS+2))
	POS3=$((POS2+39))
	(($COLS>=44)) && MENU || { echo -e "$CVA AJUSTE A TELA!\n No MÍNIMO 44 Colunas $FC" ; PCM ; }
}

GERACOR() {
	local cnt=$((1+RANDOM%31));local atb=$((RANDOM%2));
	CSM="\e["$atb";38;5;"$cnt"m"
}

MSGM() { echo -e "$CVA\n\n \" OPÇãO INVáLIDA! \" $FC" ; sleep 1 ; }

FUNCAO_01() {
	tput clear;

	read -p "Nome do novo usúario:" addusuario
	test $addusuario

	if [ $? != "1" ];
		then
		useradd $addusuario
		
		if [ $? != "1"]
		passwd $addusuario
		usermod --shell /bin/bash $addusuario
		adduser $addusuario libvirt-qemu
		adduser $addusuario libvirt
	fi
	
	sleep 0.5	
	PCM

}

FUNCAO_02() {
	tput clear ;

	echo "Lista de usuarios:" ;

	#cat /etc/passwd | tr ':' '\t' |grep "/bin/bash" |cut -f1
	#volta o usuario que possuem terminal /bin/bash

	cat /etc/passwd | tr ':' '\t' |grep "/bin/bash" |cut -f1

	sleep 0.5
	PCM
}

FUNCAO_03() {
	tput clear ;

	echo "Deletar usuário: " ;
	read -p "Nome do usúario que deseja deletar:" delusuario

#	read delusuario;
	
	cat /etc/passwd | tr ':' '\t' |cut -f1 |grep "${delusuario}" ;

	if [ $? != "1" ];
	then
		deluser $delusuario ;
	else
	echo "Usuário não existe"
	fi

	sleep 0.5
	PCM
}
FUNCAO_04() {
	tput clear ;

#	echo "Nome do usuario:"
	read -p "Nome do usúario que deseja mudar a senha:" senha_usuario
	
	cat /etc/passwd | tr ':' '\t' |cut -f1 |grep "${senha_usuario}" ;
	
	if [ $? != "1" ];
	then
		passwd $senha_usuario ;
	else
	echo -e "Usuario $senha_usuario não existe."
	fi

	sleep 0.5;
	PCM
}
PMENU
